### ISSUE TITLE
启动后运行一会儿报错

### ISSUE THREAD

**Issue by johnsonjie** [taosdata/Bailongma#8]
panic: Checktable error value type

goroutine 22 [running]:
main.SerilizeTDengine(0xc00059c5d0, 0xc0005956d0, 0xc, 0xc00059c600, 0x177289bb8b0, 0x736fdd, 0x8, 0xc000210000, 0xe, 0xc0005eb050, ...)
	/root/blm_telegraf/server.go:346 +0xc6a
main.ProcessData(0xc0000f27e0, 0x1, 0x1, 0x736fdd, 0x8, 0xc000210000, 0xe, 0x0, 0x0)
	/root/blm_telegraf/server.go:392 +0x1030
main.ProcessReq(0xc000580000, 0x4d2, 0x63f, 0xc000210000, 0xe, 0x0, 0x0)
	/root/blm_telegraf/server.go:284 +0x3d5
main.NodeProcess(0x4, 0x8, 0x9)
	/root/blm_telegraf/server.go:210 +0xce
created by main.main
	/root/blm_telegraf/server.go:139 +0x164
host: tdengine:0  port: 10202  database: telegraf%

**Comment by johnsonjie** [comment]
本地用的容器启动的

**Comment by sangshuduo** [comment]
请详细描述一下步骤
